/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYPDFV4
#define MYPDFV4

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TF2.h"
 
class MyPdfV4 : public RooAbsPdf {
public:
  MyPdfV4() {} ; 
  MyPdfV4(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _y,
	      RooAbsReal& _wNW1,
	      RooAbsReal& __rhoN1,
	      RooAbsReal& _sigxN1,
	      RooAbsReal& _sigyN1,
	      RooAbsReal& __rhoW1,
	      RooAbsReal& _sigxW1,
	      RooAbsReal& _sigyW1,
	      RooAbsReal& _wNW2,
	      RooAbsReal& _sigxN2,
	      RooAbsReal& _sigxW2);
  MyPdfV4(const MyPdfV4& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyPdfV4(*this,newname); }
  inline virtual ~MyPdfV4() { }

protected:

  RooRealProxy x ;
  RooRealProxy y ;
  RooRealProxy wNW1 ;
  RooRealProxy _rhoN1 ;
  RooRealProxy sigxN1 ;
  RooRealProxy sigyN1 ;
  RooRealProxy _rhoW1 ;
  RooRealProxy sigxW1 ;
  RooRealProxy sigyW1 ;
  RooRealProxy wNW2 ;
  RooRealProxy sigxN2 ;
  RooRealProxy sigxW2 ;
  
  TF2 *fitFuncN1N2 = new TF2("fitFuncN1N2","[4]*1./(2*3.14159*TMath::Sqrt([3]))*TMath::Exp(-0.5*(TMath::Power(x[0],2.0)*[0]+TMath::Power(x[1],2.0)*[1]+2*[2]*x[0]*x[1]))",-30,30,-30,30);
  TF2 *fitFuncN1W2 = new TF2("fitFuncN1W2","[4]*1./(2*3.14159*TMath::Sqrt([3]))*TMath::Exp(-0.5*(TMath::Power(x[0],2.0)*[0]+TMath::Power(x[1],2.0)*[1]+2*[2]*x[0]*x[1]))",-30,30,-30,30);
  TF2 *fitFuncW1N2 = new TF2("fitFuncW1N2","[4]*1./(2*3.14159*TMath::Sqrt([3]))*TMath::Exp(-0.5*(TMath::Power(x[0],2.0)*[0]+TMath::Power(x[1],2.0)*[1]+2*[2]*x[0]*x[1]))",-30,30,-30,30);
  TF2 *fitFuncW1W2 = new TF2("fitFuncW1W2","[4]*1./(2*3.14159*TMath::Sqrt([3]))*TMath::Exp(-0.5*(TMath::Power(x[0],2.0)*[0]+TMath::Power(x[1],2.0)*[1]+2*[2]*x[0]*x[1]))",-30,30,-30,30);

  Double_t evaluate() const ;

private:

  ClassDef(MyPdfV4,1) // Your description goes here...
};
 
#endif
